### ISSUE TITLE
Incorrect Airbnb credentials

### ISSUE THREAD

**Issue by jroth55** [wootwoot1234/Superhost-Tools#1]
When I enter my airbnb details on the demo on your website it says.
The Airbnb username and/or password supplied are incorrect. Please try again.

**Comment by wootwoot1234** [comment]
@jroth55, saw the error come through.  Can you do me a favor and make sure those credentials are working on Airbnb.com?  I'm looking into the error more right now.

**Comment by wootwoot1234** [comment]
@jroth55 it seems like the server is timing out while it's downloading the data from your airbnb account.  Is it possible that you have a lot of listings?  It seems like your data downloaded so refreshing the page should fix the issue.  Please report back and let me know if that didn't fix it.  It need to see what I can do to handle accounts with many listings so that this doesn't happen again.

**Comment by jroth55** [comment]
Great stuff !! Works 👍 Looking forward to playing with your software

**Comment by wootwoot1234** [comment]
Glad to hear it.  If you have some time, let me know how you like it and what could be better.
