### ISSUE TITLE
only 10 of 19 listings on account imported

### ISSUE THREAD

**Issue by ferniebnb** [wootwoot1234/Superhost-Tools#22]
I added a new account.  Only 10 of 19 listings associated with it were imported.

**Comment by ferniebnb** [comment]
So.  Finally got the account to add.  But it didn't pull all the listings associated with the account in?

Only 10 of 19 that I have on this account?

**Comment by ferniebnb** [comment]
Is there a max out of 10 listings per account perhaps?

**Comment by wootwoot1234** [comment]
@ferniebnb that error is from Airbnb. I’m not sure why but some accounts get it when logging in. Often if goes away if you try to log in later. How did you fix it? Have any tips?

There maybe an arbitrary 10 listing limit that shouldn’t be there. Let me look at the code and get back to you.

**Comment by wootwoot1234** [comment]
@ferniebnb I set the limit to 50 listings so you should be good.  You can either delete your airbnb account and re-add it (but you'll lose any rules you added) or you can wait and within 24 hours all your listings will be there (because the app will automatically recheck your account every 24 hours for new listings and listings changes).

**Comment by wootwoot1234** [comment]
@ferniebnb let me know how you fixed the "Please try again through the website or contact support if you need immediate assistance" issue.  Thanks!

**Comment by ferniebnb** [comment]
The listings came online 24 hours later.  Not sure how I got around the "Please try again through the website or contact support if you need assistance issue....   Persistence I suppose.
