### ISSUE TITLE
Message not sending after review

### ISSUE THREAD

**Issue by ASochat** [wootwoot1234/Superhost-Tools#33]
Hi there! Thanks for the great tool! I just started using it and it seems that the auto message isn't sent after the review is left on my local repo:  

My log returns 'MESSAGE ALREADY SENT OR IS DISABLED'

After a checkup of the code, I found this : 

var sentOrDisabledMessage = await Message.findOne({
                    listingID: listing._id,
                    messageRuleID: messageRule._id,
                    airbnbConfirmationCode,
                    $or: [
                        {disable: true},
                        {sentDate: {$exists: true}}
                    ]
                });
if(sentOrDisabledMessage) {
     console.log("    buildMessage() MESSAGE ALREADY SENT OR IS DISABLED");
}

So it seems like it finds a sentDate existing. Any idea where it comes from?

**Comment by wootwoot1234** [comment]
Hi Antoine,

I’m not sure what’s going on. It maybe the way it downloads the review
information from Airbnb? I’m working on a complete rewrite of the code so
I’m no longer supporting this code base. If you find the bug, send me a
pull request it’s the fix. Superhosttools.com is using the new code base if
you don’t feel like debugging the code, it doesn’t have this bug. :)

**Comment by FelixMalfait** [comment]
Hi @wootwoot1234 
Thanks for the amazing work.
You're not planning to publish the new codebase (not a blame - I totally understand - just a question :))?

**Comment by wootwoot1234** [comment]
@FelixMalfait Right now the code needs a lot more work before I consider releasing it.  I'm not sure what my plans are, right now I'm just having fun trying to make it work really well.  :)

**Comment by FelixMalfait** [comment]
Ok thanks @wootwoot1234 - we are only using the review side but we're getting a lot of bugs right now. Having it on our server is super useful because I can connect it to our internal databases and really customize the software (e.g. automatically disable review when an incident is registered in our DB, track review received and link it to review we sent etc...). 
I know money is not your motive, but just to be fully transparent with you, we'd be willing to pay to have access to the code [maybe I shouldn't say this and I'm ruining all the beauty of open source - nice people sharing... Some intermediate solution with mandatory license for company and not individuals might be a solution...].

**Comment by wootwoot1234** [comment]
@FelixMalfait I'd love to hear more about how you're using the code and how I can help.   Send me an email so we can chat more.  tkrones@gmail.com
