### ISSUE TITLE
AddAccount error

### ISSUE THREAD

**Issue by OlegBilous** [wootwoot1234/Superhost-Tools#51]
I've deployed GitHub repo to my localhost.
But addAccount is not working for some Airbnb accounts even though some are working fine.

**Comment by wootwoot1234** [comment]
Airbnb updated the way they handle authentication over their api and it got much more complicated.  The easiest solution is to wait 24 hours and try to login with those accounts again, some people have reported success with that.

Superhosttools.com is now using a different code base with the login issue fixed if you just want to sign up for an account there.

**Comment by wootwoot1234** [comment]
Hey @FelixMalfait,

Thanks for the tip on http://luminati.io/, I hadn't heard of them and I might need it in the future.  :)

It looks like Airbnb might have changed their sign-in procedure again which is why you're having trouble adding your account.  I see some errors in the logs and I'm going to look into it more and get back to you.  

Tom
